// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "PoliAPI",
            "email": "eliasgill42@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "get": {
                "description": "Iniciar sesion en una cuenta de usuario y generar un token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Iniciar Sesion",
                "parameters": [
                    {
                        "maxLength": 30,
                        "minLength": 5,
                        "type": "string",
                        "description": "Nombre del usuario",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maxLength": 30,
                        "minLength": 5,
                        "type": "string",
                        "description": "La contrasena",
                        "name": "paswd",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Parametros invalidos",
                        "schema": {
                            "type": "query"
                        }
                    }
                }
            }
        },
        "/register": {
            "put": {
                "description": "Crear una nueva cuenta de usuario",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Crear cuenta",
                "parameters": [
                    {
                        "maxLength": 30,
                        "minLength": 5,
                        "type": "string",
                        "description": "Nombre del usuario",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maxLength": 30,
                        "minLength": 5,
                        "type": "string",
                        "description": "La contrasena",
                        "name": "paswd",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Parametros invalidos",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Api para posible politerminal web",
	Description:      "API sencilla para manejar los horarios de la facultad",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
